name: Backend CI/CD

on:
  push:
    branches:
      - main
      - RTR-backend
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"

  workflow_dispatch:

env:
  IMAGE_NAME: 2024dock/cdc-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "TAG=v1.0.${{ github.run_number }}" >> $GITHUB_ENV
          echo "SHA_TAG=$SHORT_SHA" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.SHA_TAG }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Image
        run: |
          docker build -t backend-test .

      - name: Output Image
        run: |
          echo "Backend Image Published"
          echo "${IMAGE_NAME}:${TAG}"